### ISSUE TITLE
Switch on library evolution support in the iOS-TicketmasterSDK

### ISSUE THREAD

**Issue by samsiuatpurple** [ticketmaster/iOS-TicketmasterSDK#1]
G'day team,

We are using the Ticketmaster SDK (https://github.com/ticketmaster/iOS-TicketmasterSDK) v1.3.0

When I am writing the code, the following error is prompted,

`Failed to build module 'TicketmasterAuthentication'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.`

OS: 14.0 (23A344)
Xcode: Version 15.0 (15A240d)

Per https://www.swift.org/blog/library-evolution/, is it possible to switch on library evolution support so we can use this SDK without error?

Thanks!

**Comment by ppluskota** [comment]
@jbackertm can we get some feedback? I have the same issue

**Comment by jbackertm** [comment]
Ignite now requires iOS 15.0+, and it is built using Xcode 15.0.1 (15A507), Swift 5.9 (5.9.0.128.108).

That should resolve this issue.
