### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by ohsnapitscolin** [ticketmaster/iOS-TicketmasterSDK#3]
Hey all, I'm trying to create a Ticketmaster pod that can be used easily inside of a React Native app, but unfortunately I can't add a Swift Package Manager dependency to my pod. I was hoping we might be able to publish this Ticketmaster SDK to CocoaPods in addition to SPM.

Based on the [podspec](https://github.com/ticketmaster/iOS-PSDK-Pod/blob/master/TM-PSDK.podspec) for the legacy PresenceSDK, it seems like this should be a pretty quick addition.

**Comment by jbackertm** [comment]
Very reasonable. I'll add it.

**Comment by jbackertm** [comment]
Added CocoaPods support to current and all previous verions.
